The Simple Structure of a NN :-
X or $a^{0}$ or Input Layer/Vector ----> Hidden Layer or $a^{1}$, $a^{2}$, ....., $a^{n}$ ----> OutPut Layer or $\hat{y}$

For each set of Hidden layer we have Neurons and Neurons are the part where all the math's happens

Q. What Single Neuron Do in Forward Propagation?

Input = $a^{l-1}$
Output = $a^{l}$ Input Value Needed for the Next Layer

$z^{l}$ = $w^{l}$ * $a^{l-1}$ + $b^{l}$

$a^{l}$ = $g^{l}$($z^{l}$) :: Where $g^{l}$ is the Activation Function for that Neuron

For Implementation We also Store the Values of :- $z^{l}$, $w^{l}$, $b^{l}$

Q. For Backward Propagation we adjust the values of Weights $w^{l}$, $b^{l}$ ?

We do  Gradient Descent on the Cost Function which is Sum of Loss Function 

Input = $da^{l}$ is the Partial Derivative of dw/da ((((???))))

Output = $da^{l-1}$, $dw^{l}$, $db^{l}$

$dz^{l}$ = $da^{l}$ * $g^{l}z^{l}$

$dw^{l}$ = $dz^{l}$ * $\mathbf{a^{l-1}}^\top$

$db^{l}$ = $dz^{l}$

$da^{l-1}$ = $\mathbf{w^{l}}^\top$ * $dz^{l}$


After Every Step of Backward Propagation The Values of $a^{1}$ Will be

??????

Our NN will have a simple two-layer architecture. Input layer $a^{[0]}$ will have 784 units corresponding to the 784 pixels in each 28x28 input image. A hidden layer $a^{[1]}$ will have 10 units with ReLU activation, and finally our output layer $a^{[2]}$ will have 10 units corresponding to the ten digit classes with softmax activation.

**Forward propagation**

$$Z^{[1]} = W^{[1]} X + b^{[1]}$$
$$A^{[1]} = g_{\text{ReLU}}(Z^{[1]}))$$
$$Z^{[2]} = W^{[2]} A^{[1]} + b^{[2]}$$
$$A^{[2]} = g_{\text{softmax}}(Z^{[2]})$$

**Backward propagation**

$$dZ^{[2]} = A^{[2]} - Y$$
$$dW^{[2]} = \frac{1}{m} dZ^{[2]} A^{[1]T}$$
$$dB^{[2]} = \frac{1}{m} \Sigma {dZ^{[2]}}$$
$$dZ^{[1]} = W^{[2]T} dZ^{[2]} .* g^{[1]\prime} (z^{[1]})$$
$$dW^{[1]} = \frac{1}{m} dZ^{[1]} A^{[0]T}$$
$$dB^{[1]} = \frac{1}{m} \Sigma {dZ^{[1]}}$$

**Parameter updates**

$$W^{[2]} := W^{[2]} - \alpha dW^{[2]}$$
$$b^{[2]} := b^{[2]} - \alpha db^{[2]}$$
$$W^{[1]} := W^{[1]} - \alpha dW^{[1]}$$
$$b^{[1]} := b^{[1]} - \alpha db^{[1]}$$

In [4]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

Output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias

print(Output)

2.3


In [5]:
# Layers This is a layer of Where inputs are the values we got from the  Previses Layers and 
# So Baicely A^l and Weights and Bias are the values from each 

inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
print (output)

[4.8, 1.21, 2.385]


In [12]:
# Cleaner Version of Layers

inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
[0.5, -0.91, 0.26, -0.5],
[-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_outputs = [] # Output of current layer
for neuron_weights, neuron_bias in zip(weights, biases) : # Zip combine Two List Element Wise eg W = [1.5, 2.3, 3.5] & B = [1, 6, 5] Zip(W,B) will be [[1.5, 1], [2.3, 6], [3.5, 5]]
    neuron_output = 0 # Output of given neuron
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_outputs. append (neuron_output)

print(layer_outputs)


[4.8, 1.21, 2.385]


In [10]:
# Dot Product Single
import numpy as np

inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

Output = np.dot(weights, inputs) + bias

print(Output)

2.3


In [14]:
# Layer using Dot Product

inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
[0.5, -0.91, 0.26, -0.5],
[-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

Output = np.dot(weights, inputs) + biases

print(Output)

[4.8   1.21  2.385]


In [16]:
# Why Need to Transpose Shape Did not Match for Weights and Input Matrixes
# This Single Layer for Batches  Img For understanding should be in 

inputs = [[1, 2, 3, 2.5],
[2.0, 5.0, -1.0, 2.0],
[-1.5, 2.7, 3.3, -0.8]]

weights =[[0.2, 0.8, - 0.5, 1.0],
[0.5, -0.91, 0.26, -0.5],
[-0.26, -0.27, 0.17, 0.87] ]

biases = [2, 3, 0.5]

output = np.dot (inputs, np.array(weights) .T) + biases
print (output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [20]:
X=[[1, 2, 3, 2.5],
[2.0, 5.0, -1.0, 2.0],
[-1.5, 2.7, 3.3, -0.8]]

In [21]:
np.random.seed(0)

def Layer_Dense(n_input, n_neuron):
    Weights = 0.10 * np.random.randn(n_input, n_neuron)
    Biases = np.zero((1, n_neuron))
    return Weights, Biases

def Forward(inputs,Weights,Biases ):
    output = np.dot(inputs, Weights) + Biases
    return output


In [34]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
#print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.11393755 -0.01423452]
 [ 0.04397295 -0.11042021]
 [ 0.11655307 -0.04529458]]
